### PR TITLE
Allow installing with symfony 3

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping @philipobenito.

**Comment by philipobenito** [comment]
I need time to check BC breaks to before I can merge this.

**Comment by hannesvdvreken** [comment]
Not sure if you're aware, you probably are. Symfony 3.0 has no breaking changes, except for removed deprecated functionality. If some functionality were to be deprecated, you'd have seen it, or someone would have created an issue for it saying "your code is thowing these warnings".

**Comment by GrahamCampbell** [comment]
Yeh, if it's broken on 3.0, it's broken on 2.x anyway.

**Comment by philipobenito** [comment]
Ah, this I didn't know, will merge and tag in the morning.

**Comment by hannesvdvreken** [comment]
Ok, wasn't sure, but good thing I mentioned it anyway then :wink:

**Comment by philipobenito** [comment]
I did think it odd that there was no PSR-7 but just haven't had time to look at what the version bump was.

Thanks both of you.

**Pull request merged**
