### PR TITLE
Upgrade to stable fast route

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
Maybe do `^0.7|^1.0`, no?

**Comment by philipobenito** [comment]
Already planned for 3.x

**Comment by GrahamCampbell** [comment]
> Maybe do ^0.7|^1.0, no?

:-1: for that if it's happening in 3.x.

**Comment by hannesvdvreken** [comment]
Yes you're right 😉

**Pull request closed without merging**
