### PR TITLE
Allow route arguments to be passed in to controller of MethodArgumentStrategy

### PR DESCRIPTION
**Pull request by hannesvdvreken**
The `MethodArgumentStrategy` allows you to inject anything into the controller method.

```php
class HelloController
{
    protected $repository;

    public function __construct(Repository $repository)
    {
        $this->repository = $repository;
    }

    public function index(Validator $validator, Request $request)
    {
         $filter = $request->get('filter');

         $validator->validate(compact('filter'));
         ...
    }
}
```

But with this simple change you can do this:

```php
class HelloController
{
    protected $repository;

    public function __construct(Repository $repository)
    {
        $this->repository = $repository;
    }

    public function show(ViewFactory $view, $name)
    {
         $user = $this->repository->findByName($name);
         return $view->render('user/show.twig', compact('user'));
    }
}
```

```php
$router = new League\Route\RouteCollection();
$router->setStrategy(new MethodArgumentStrategy());

$router->get('/user/{name}', 'UserController::show');

$response = $router->getDispatcher()->dispatch('GET', '/users/username');
```

### CODE REVIEW

**Comment by philipobenito** [comment]
@hannesvdvreken slight change coming to league/container to handle this situation better, will merge with that change

**Comment by philipobenito** [comment]
@hannesvdvreken actually think this change will work as is for now, have you tested?

**Comment by hannesvdvreken** [comment]
I tested it. Want the index.php I used? https://gist.github.com/hannesvdvreken/1cafda37716ff4bed709

**Comment by philipobenito** [comment]
Thanks, I'll look through this, I see a small potential issue if the callable is registered with the container but I'll test it out

**Comment by philipobenito** [comment]
This is to be merged when league/container handles this consistently. It will only currently work with reflection, plan to pick up the task on container in the coming days.

**Comment by hannesvdvreken** [comment]
@philipobenito any update on this?

**Comment by philipobenito** [comment]
Going to have a look at it on Sunday, in the meantime, if you have any thoughts on how this could be cleanly achieved within the container I'm open to them.

**Comment by philipobenito** [comment]
I suppose one option would be to just use reflection regardless of whether the callable is defined, but only reflect for extra params.

**Comment by hannesvdvreken** [comment]
How do you mean "only reflect for the extra params"?

The only change this PR does is it passes the URL params when they have the same name as the controller method.

**Comment by hannesvdvreken** [comment]
:ok_hand: ok, check it out on sunday ;-)

**Comment by philipobenito** [comment]
This PR is perfect for any callables that are not manually defined within the container. However, the container allows you to define your callables to avoid using refection right now using the `invokable` method, if that has been done, then this will fail :-( so my plan is to fix the container so this will work regardless of whether the callable has been defined or not.

**Comment by hannesvdvreken** [comment]
I see now. I'll have a look as well if I can find some time this weekend. May have taken on too much OS commitments lately.

**Comment by philipobenito** [comment]
Not a problem, I'll definitely be looking at it on Sunday either way, but your input has been really valuable lately so wanted to ask your opinion

**Comment by philipobenito** [comment]
Been having a look today, will hopefully have a working solution next couple of days

**Comment by hannesvdvreken** [comment]
Added a commit which requires an added method from thephpleague/container#28.

**Pull request closed without merging**
