### PR TITLE
Add route arguments in the MethodArgument Strategy

### PR DESCRIPTION
**Pull request by TishoTM**
We can determine if it is closure or a class with its method, retrieve all the dependencies and also pass the route arguments.

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
I suggest you read the documentation on `$container->call`. I suggested this PR (#12) which will do exactly what you need.

**Comment by philipobenito** [comment]
The only thing slowing this down is that it will only currently work for
reflection based resolution, working on a solution so it will work on
defined methods too.

**Comment by TishoTM** [comment]
Actually, saw the #12 after I pulled mine.
I was following the other strategies (RequestResponseStrategy and RestfulStrategy) concept of returning an associative array of the arguments as a last method argument.

The Hannes' solution is slightly different and actually is better approach for passing the arguments this way in all the strategies and be consistent.

**Comment by philipobenito** [comment]
This is solved by #12 which will be merged in the coming days.

**Pull request closed without merging**
