### PR TITLE
Added test for ContainerAwareTrait

### PR DESCRIPTION
**Pull request by ricardofiorani**

### CODE REVIEW

**Comment by philipobenito** [comment]
Please take note of the coding standards and tools already used in this library. Even tests require docblocks and we do not currently use prophesize.

**Comment by ricardofiorani** [comment]
@philipobenito prophesize comes with phpunit now so I thought it was ok to use. Please let me know which strategy for mocking objects is preferable.

**Comment by philipobenito** [comment]
I know but the rest of the tests currently use the normal phpunit mocking framework so I’d rather keep consistency for now

**Comment by philipobenito** [comment]
Closing as stale and no response

**Pull request closed without merging**
