### PR TITLE
travis: PHP 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**
See http://docs.travis-ci.com/user/languages/php/#PHP-7

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
Maybe it's safer to allow failures as this depends on a nightly build environment.

**Comment by hannesvdvreken** [comment]
It passes, though: https://travis-ci.org/thephpleague/route/jobs/52402226

**Comment by TomasVotruba** [comment]
@hannesvdvreken If it would not, I'd add it to allowed failures. Otherwise it makes no sense.

**Comment by hannesvdvreken** [comment]
Yeah but the thing is, the build environment can always change. So it passes now, but that doesn't mean it will pass on every build in the future. It's safer to allow failures and fix them if they occur, but not let PRs block because some nightly platform requirement makes the build fail.

**Comment by philipobenito** [comment]
Because we can't yet be aware of what's changing in PHP 7, allowing failure is the way to go, I need to make a couple of changes to Scrutinizer config too before I merge.

**Comment by hannesvdvreken** [comment]
@TomasVotruba Can you add these lines please? https://github.com/laravel/framework/blob/5.0/.travis.yml#L10-L12 Thanks for the PR!

**Comment by TomasVotruba** [comment]
@hannesvdvreken  Done.

@philipobenito It should be ready now.

**Comment by hannesvdvreken** [comment]
@TomasVotruba perfect!

**Comment by philipobenito** [comment]
:+1: Thanks

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
