### PR TITLE
Initial 5.x

### PR DESCRIPTION
**Pull request by philipobenito**
Here are the initial 5.x changes.

TODO:
- Add 5.x documentation
- Refactor and add more unit tests

Input welcome.

### CODE REVIEW

**Comment by memran** [comment]
My little inputs are here:

1. Subdomain Routing [it will help for SaaS application]
2. Fallback Routing [user may define a callable route that will be executed when no other route matches the incoming request.]
3. Route Name [ set and get method]
4. Route Group Name [ set and get method]
5. Load Routes initially and Dispatch later to support like swoolephp or reactphp http server

**Comment by philipobenito** [comment]
@memran most of that is either existing functionality or is covered in this PR, the only thing that isn't specifically there is your second point, because it's not really recommended, and should be handled by creating a custom strategy with a handler for not found routes.

**Comment by memran** [comment]
> @memran most of that is either existing functionality or is covered in this PR, the only thing that isn't specifically there is your second point, because it's not really recommended, and should be handled by creating a custom strategy with a handler for not found routes.

Right. I am using custom strategy with middleware. it will be easier to have option as route declarative.Though it is optional.

**Comment by TMschar** [comment]
Hey! What is the status of this PR? Anyway I can help? Whats the plan for 7.4 support / upcoming 8 support?

**Comment by philipobenito** [comment]
@SimZor I was aiming for a release last week but I've had flu so now aiming for some point in the next two weeks.

The main thing that would be helpful for anyone that wants to help would be to extensively test the cached router implementation, try to break it and tell me how you broke it.

**Pull request closed without merging**
